import { HomeContainer, Product } from '@/styles/pages/home'
import Image from 'next/image'
import Head from 'next/head'

import shirt1 from '../assets/shirts/1.png'
import shirt2 from '../assets/shirts/2.png'
import shirt3 from '../assets/shirts/3.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContainer>
        <Product>
          <Image src={shirt1} width={520} height={480} alt="" />

          <footer>
            <strong> Shirt 1</strong>
            <span> 50€</span>
          </footer>
        </Product>

        <Product>
          <Image src={shirt2} width={520} height={480} alt="" />

          <footer>
            <strong> Shirt 2</strong>
            <span> 55€</span>
          </footer>
        </Product>

        <Product>
          <Image src={shirt3} width={520} height={480} alt="" />

          <footer>
            <strong> Shirt 3</strong>
            <span> 7 5€</span>
          </footer>
        </Product>
      </HomeContainer>
    </>
  )
}
